/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author AJS
 */
public class posttest2 extends javax.swing.JFrame {

    /**
     * Creates new form posttest2
     */
    public posttest2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jColorChooser2 = new javax.swing.JColorChooser();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        tempat = new javax.swing.JLabel();
        jk = new javax.swing.JLabel();
        alamat = new javax.swing.JLabel();
        rr = new javax.swing.JLabel();
        kd = new javax.swing.JLabel();
        kecamatan = new javax.swing.JLabel();
        kota = new javax.swing.JLabel();
        agama = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        gd = new javax.swing.JLabel();
        pekerjaan = new javax.swing.JLabel();
        jnama = new javax.swing.JTextField();
        jttl1 = new javax.swing.JTextField();
        jpria = new javax.swing.JRadioButton();
        jwanita = new javax.swing.JRadioButton();
        jalamat = new javax.swing.JTextField();
        jpekerjaan = new javax.swing.JTextField();
        jkec = new javax.swing.JTextField();
        jkel = new javax.swing.JTextField();
        jrt1 = new javax.swing.JTextField();
        jkota = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jrt2 = new javax.swing.JTextField();
        jagama = new javax.swing.JComboBox<>();
        jstatus = new javax.swing.JComboBox<>();
        jgoldar = new javax.swing.JComboBox<>();
        jwna = new javax.swing.JRadioButton();
        jwni = new javax.swing.JRadioButton();
        jreset = new javax.swing.JButton();
        jregis = new javax.swing.JButton();
        kewarganegaraan = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jttl2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 204, 153));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("FORM ISIAN");

        jLabel2.setBackground(new java.awt.Color(255, 255, 0));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("FORM KARTU TANDA PENDUDUK");

        nama.setBackground(new java.awt.Color(255, 255, 255));
        nama.setText("Nama :");

        tempat.setText("Tempat/Tanggal Lahir :");

        jk.setText("Jenis Kelamin :");

        alamat.setText("Alamat :");

        rr.setText("RT/RW :");

        kd.setText("Kel/Desa :");

        kecamatan.setText("Kecamatan :");

        kota.setText("Kota :");

        agama.setText("Agama :");

        status.setText("Status :");

        gd.setText("Golongan Darah :");

        pekerjaan.setText("Pekerjaan :");

        jttl1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jttl1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jpria);
        jpria.setText("Pria");

        buttonGroup1.add(jwanita);
        jwanita.setText("Wanita");

        jpekerjaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpekerjaanActionPerformed(evt);
            }
        });

        jLabel17.setText("/");

        jagama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ISLAM", "KRISTEN", "HINDU", "BUDHA", " " }));

        jstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KAWIN", "BELUM KAWIN" }));

        jgoldar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "AB", "O" }));
        jgoldar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jgoldarActionPerformed(evt);
            }
        });

        buttonGroup2.add(jwna);
        jwna.setText("WNA");

        buttonGroup2.add(jwni);
        jwni.setText("WNI");
        jwni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jwniActionPerformed(evt);
            }
        });

        jreset.setText("Reset");
        jreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jresetActionPerformed(evt);
            }
        });

        jregis.setText("Register");
        jregis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jregisActionPerformed(evt);
            }
        });

        kewarganegaraan.setText("Kewarganegaraan");

        jLabel3.setText("/");

        jttl2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jttl2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kota)
                            .addComponent(kecamatan)
                            .addComponent(kd)
                            .addComponent(rr))
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tempat)
                            .addComponent(pekerjaan)
                            .addComponent(kewarganegaraan)
                            .addComponent(gd)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(agama)
                                .addComponent(status))
                            .addComponent(alamat)
                            .addComponent(jk)
                            .addComponent(nama))
                        .addGap(43, 43, 43)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jrt1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrt2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jwna)
                        .addGap(18, 18, 18)
                        .addComponent(jwni))
                    .addComponent(jkel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jkec)
                    .addComponent(jkota)
                    .addComponent(jpekerjaan, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jttl1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jpria)
                                .addGap(18, 18, 18)
                                .addComponent(jwanita)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jttl2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jnama)
                    .addComponent(jalamat, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jgoldar, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jagama, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jstatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jreset))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jregis))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(206, 206, 206))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nama)
                                    .addComponent(jnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tempat)
                                    .addComponent(jttl1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jttl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jk, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(alamat))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jpria)
                                            .addComponent(jwanita))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jalamat, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rr)
                                    .addComponent(jrt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17)
                                    .addComponent(jrt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jkel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kd, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jkec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kecamatan))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(kota)
                                .addGap(7, 7, 7))
                            .addComponent(jkota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(agama))
                    .addComponent(jagama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(status)
                    .addComponent(jstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gd)
                    .addComponent(jgoldar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pekerjaan)
                    .addComponent(jpekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jwna)
                    .addComponent(jwni)
                    .addComponent(kewarganegaraan))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jreset)
                    .addComponent(jregis)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jttl2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jttl2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jttl2ActionPerformed

    private void jregisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jregisActionPerformed
        // TODO add your handling code here:
        String Nama,Tempat1,Tempat2,Jk=null,Alamat,Rr,Rw,Kd,Kecamatan,Kota,Agama,Status,Gd,Pekerjaan,Kg=null;
        Nama = jnama.getText();
        Tempat1 = jttl1.getText();
        Tempat2 = jttl2.getText();
        if (jpria.isSelected())
        {Jk = jpria.getText();}
        else if (jwanita.isSelected())
        {Jk = jwanita.getText();}
        Alamat = jalamat.getText();
        Rr = jrt1.getText();
        Rw = jrt2.getText();
        Kd = jkel.getText();
        Kecamatan = jkec.getText();
        Kota = jkota.getText();
        Agama = jagama.getSelectedItem().toString();
        Status = jstatus.getSelectedItem().toString();
        Gd = jgoldar.getSelectedItem().toString();
        Pekerjaan = jpekerjaan.getText();
        if (jwna.isSelected())
        {Kg = jwna.getText();}
        else if (jwni.isSelected())
        {Kg = jwni.getText();}

        Output x=new Output(Nama,Tempat1,Tempat2,Jk,Alamat,Rr,Rw,Kd,Kecamatan,Kota,Agama,Status,Gd,Pekerjaan,Kg);
        x.setVisible(true);

    }//GEN-LAST:event_jregisActionPerformed

    private void jresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jresetActionPerformed
        // TODO add your handling code here:
        jnama.setText("");
        jttl1.setText("");
        jttl2.setText("");
        jalamat.setText("");
        buttonGroup1.clearSelection();
        jrt1.setText("");
        jrt2.setText("");
        jkel.setText("");
        jkec.setText("");
        jkota.setText("");
        jpekerjaan.setText("");
        buttonGroup2.clearSelection();
        jagama.setSelectedItem(null);
        jstatus.setSelectedItem(null);
        jgoldar.setSelectedItem(null);

    }//GEN-LAST:event_jresetActionPerformed

    private void jwniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jwniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jwniActionPerformed

    private void jgoldarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jgoldarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jgoldarActionPerformed

    private void jpekerjaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpekerjaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpekerjaanActionPerformed

    private void jttl1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jttl1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jttl1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(posttest2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(posttest2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(posttest2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(posttest2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new posttest2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agama;
    private javax.swing.JLabel alamat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel gd;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JColorChooser jColorChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jagama;
    private javax.swing.JTextField jalamat;
    private javax.swing.JComboBox<String> jgoldar;
    private javax.swing.JLabel jk;
    private javax.swing.JTextField jkec;
    private javax.swing.JTextField jkel;
    private javax.swing.JTextField jkota;
    private javax.swing.JTextField jnama;
    private javax.swing.JTextField jpekerjaan;
    private javax.swing.JRadioButton jpria;
    private javax.swing.JButton jregis;
    private javax.swing.JButton jreset;
    private javax.swing.JTextField jrt1;
    private javax.swing.JTextField jrt2;
    private javax.swing.JComboBox<String> jstatus;
    private javax.swing.JTextField jttl1;
    private javax.swing.JTextField jttl2;
    private javax.swing.JRadioButton jwanita;
    private javax.swing.JRadioButton jwna;
    private javax.swing.JRadioButton jwni;
    private javax.swing.JLabel kd;
    private javax.swing.JLabel kecamatan;
    private javax.swing.JLabel kewarganegaraan;
    private javax.swing.JLabel kota;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel pekerjaan;
    private javax.swing.JLabel rr;
    private javax.swing.JLabel status;
    private javax.swing.JLabel tempat;
    // End of variables declaration//GEN-END:variables
}
